
#ifndef ELEMENTAL_SQL_IMPLEMENTATION_DELETEFROMSTATEMENT_H
#define ELEMENTAL_SQL_IMPLEMENTATION_DELETEFROMSTATEMENT_H

#include "Statement.h"

class DeleteFromStatement : public Statement {

};


#endif //ELEMENTAL_SQL_IMPLEMENTATION_DELETEFROMSTATEMENT_H
