
#ifndef ELEMENTAL_SQL_IMPLEMENTATION_DROPTABLESTATEMENT_H
#define ELEMENTAL_SQL_IMPLEMENTATION_DROPTABLESTATEMENT_H

#include "Statement.h"

class DropTableStatement : public Statement {

};


#endif //ELEMENTAL_SQL_IMPLEMENTATION_DROPTABLESTATEMENT_H
