
#ifndef ELEMENTAL_SQL_IMPLEMENTATION_INNERJOINSTATEMENT_H
#define ELEMENTAL_SQL_IMPLEMENTATION_INNERJOINSTATEMENT_H

#include "Statement.h"

class InnerJoinStatement : public Statement {

};


#endif //ELEMENTAL_SQL_IMPLEMENTATION_INNERJOINSTATEMENT_H
