
#ifndef ELEMENTAL_SQL_IMPLEMENTATION_INSERTINTOSTATEMENT_H
#define ELEMENTAL_SQL_IMPLEMENTATION_INSERTINTOSTATEMENT_H

#include "Statement.h"

class InsertIntoStatement : public Statement {

};


#endif //ELEMENTAL_SQL_IMPLEMENTATION_INSERTINTOSTATEMENT_H
