
#ifndef ELEMENTAL_SQL_IMPLEMENTATION_UPDATESTATEMENT_H
#define ELEMENTAL_SQL_IMPLEMENTATION_UPDATESTATEMENT_H

#include "Statement.h"

class UpdateStatement : public Statement {

};


#endif //ELEMENTAL_SQL_IMPLEMENTATION_UPDATESTATEMENT_H
